/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DestinosRouteImport } from './routes/destinos'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanejarViagemRouteImport } from './routes/planejar-viagem'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as DestinosSlugRouteImport } from './routes/destinos_.$slug'
import { Route as ExperienciasSlugRouteImport } from './routes/experiencias_.$slug'
import { Route as PagamentosPagamentoIdRouteImport } from './routes/pagamentos_.$pagamentoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosRoute = DestinosRouteImport.update({
  id: '/destinos',
  path: '/destinos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejarViagemRoute = PlanejarViagemRouteImport.update({
  id: '/planejar-viagem',
  path: '/planejar-viagem',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosSlugRoute = DestinosSlugRouteImport.update({
  id: '/destinos_/$slug',
  path: '/destinos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasSlugRoute = ExperienciasSlugRouteImport.update({
  id: '/experiencias_/$slug',
  path: '/experiencias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosPagamentoIdRoute = PagamentosPagamentoIdRouteImport.update({
  id: '/pagamentos_/$pagamentoId',
  path: '/pagamentos/$pagamentoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/destinos': typeof DestinosRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/planejar-viagem': typeof PlanejarViagemRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/pagamentos/$pagamentoId': typeof PagamentosPagamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/destinos': typeof DestinosRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/planejar-viagem': typeof PlanejarViagemRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/pagamentos/$pagamentoId': typeof PagamentosPagamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/destinos': typeof DestinosRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/pagamentos': typeof PagamentosRoute
  '/perfil': typeof PerfilRoute
  '/planejar-viagem': typeof PlanejarViagemRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/destinos_/$slug': typeof DestinosSlugRoute
  '/experiencias_/$slug': typeof ExperienciasSlugRoute
  '/pagamentos_/$pagamentoId': typeof PagamentosPagamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/destinos'
    | '/experiencias'
    | '/login'
    | '/pagamentos'
    | '/perfil'
    | '/planejar-viagem'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/destinos/$slug'
    | '/experiencias/$slug'
    | '/pagamentos/$pagamentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/destinos'
    | '/experiencias'
    | '/login'
    | '/pagamentos'
    | '/perfil'
    | '/planejar-viagem'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/destinos/$slug'
    | '/experiencias/$slug'
    | '/pagamentos/$pagamentoId'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/contato'
    | '/destinos'
    | '/experiencias'
    | '/login'
    | '/pagamentos'
    | '/perfil'
    | '/planejar-viagem'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/destinos_/$slug'
    | '/experiencias_/$slug'
    | '/pagamentos_/$pagamentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  DestinosRoute: typeof DestinosRoute
  ExperienciasRoute: typeof ExperienciasRoute
  LoginRoute: typeof LoginRoute
  PagamentosRoute: typeof PagamentosRoute
  PerfilRoute: typeof PerfilRoute
  PlanejarViagemRoute: typeof PlanejarViagemRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  DestinosSlugRoute: typeof DestinosSlugRoute
  ExperienciasSlugRoute: typeof ExperienciasSlugRoute
  PagamentosPagamentoIdRoute: typeof PagamentosPagamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos': {
      id: '/destinos'
      path: '/destinos'
      fullPath: '/destinos'
      preLoaderRoute: typeof DestinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejar-viagem': {
      id: '/planejar-viagem'
      path: '/planejar-viagem'
      fullPath: '/planejar-viagem'
      preLoaderRoute: typeof PlanejarViagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos_/$slug': {
      id: '/destinos_/$slug'
      path: '/destinos/$slug'
      fullPath: '/destinos/$slug'
      preLoaderRoute: typeof DestinosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias_/$slug': {
      id: '/experiencias_/$slug'
      path: '/experiencias/$slug'
      fullPath: '/experiencias/$slug'
      preLoaderRoute: typeof ExperienciasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos_/$pagamentoId': {
      id: '/pagamentos_/$pagamentoId'
      path: '/pagamentos/$pagamentoId'
      fullPath: '/pagamentos/$pagamentoId'
      preLoaderRoute: typeof PagamentosPagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  DestinosRoute: DestinosRoute,
  ExperienciasRoute: ExperienciasRoute,
  LoginRoute: LoginRoute,
  PagamentosRoute: PagamentosRoute,
  PerfilRoute: PerfilRoute,
  PlanejarViagemRoute: PlanejarViagemRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  DestinosSlugRoute: DestinosSlugRoute,
  ExperienciasSlugRoute: ExperienciasSlugRoute,
  PagamentosPagamentoIdRoute: PagamentosPagamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
